# Generated by Django 4.1.1 on 2022-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
    ]
